---

- hosts: master
  tasks:


    - name   : Download switch
      get_url:
        url : http://www-sop.inria.fr/members/Damien.Saucez/images/switch.tar.gz
        dest: ~/switch.tar.gz
        mode: 0666

    - name   : Download ubuntu18:04
      get_url:
        url : http://www-sop.inria.fr/members/Damien.Saucez/images/ubuntu.tar.gz
        dest: ~/ubuntu.tar.gz
        mode: 0666

- hosts      : all
  remote_user: ubuntu
  become     : true
  tasks      :
    - name: install python3-pip
      apt :
        update_cache: true
        name        : python3-pip

    - name: install ethtool
      apt :
        name: ethtool

    - name: install sqlite3
      apt:
        name: sqlite3

    - name: install ryu
      apt :
        name: python-ryu

    - name: install bridge-utils
      apt :
        name: bridge-utils

    - name: install net-tools
      apt :
        name: net-tools

    - name: install pexpect
      pip :
        name: pexpect

    - name: install ovs
      apt :
        name: openvswitch-switch


- hosts      : workers
  remote_user: ubuntu
  become     : true
  tasks      :
    - name   : remove root block
      command: sudo rm -f /root/.ssh/authorized_keys

    - name   : allow root access
      command: sudo cp /home/ubuntu/.ssh/authorized_keys /root/.ssh/authorized_keys


