---

- hosts      : all
  remote_user: root
  vars       :
    master_ip: "{{ master_ip }}"
  tasks      :
    - name  : master lxd configuration
      expect:
        echo     : yes
        command  : lxd init
        timeout  : 20
        responses:
          (?i)Would you like to use LXD clustering?                                       : "no"
          (?i)Do you want to configure a new storage pool?                                : "yes"
          (?i)Name of the new storage pool                                                : "default"
          (?i)Name of the storage backend to use                                          : "btrfs"
          (?i)Create a new BTRFS pool?                                                    : "yes"
          (?i)Would you like to use an existing block device?                             : "no"
          (?i)Would you like to connect to a MAAS server?                                 : "no"
          (?i)Size in GB of the new loop device                                           : "15GB"
          (?i)Would you like to configure LXD to use an existing bridge or host interface?: "no"
          (?i)Would you like to create a new local network bridge?                        : "no"
          (?i)Would you like LXD to be available over the network                         : "no"
          (?i)Would you like stale cached images to be updated automatically?             : "no"
          (?i)Would you like a YAML                                                       : "no"


- hosts      : workers
  remote_user: root
  vars       :
    master_ip: "{{ master_ip }}"
  tasks      :
    - name   : distribute switch image
      copy   :
        src  : ~/switch.tar.gz
        dest : ~/switch.tar.gz

    - name   : distribute ubuntu image
      copy   :
        src  : ~/ubuntu.tar.gz
        dest : ~/ubuntu.tar.gz



- hosts      : all
  remote_user: root
  vars       :
    master_ip: "{{ master_ip }}"
  tasks      :
    - name   : create switch image
      command: lxc image import ~/switch.tar.gz --alias switch --public

    - name   : create ubuntu18.04 image -- alias ubuntu
      command: lxc image import ~/ubuntu.tar.gz --alias ubuntu --public


